### ISSUE TITLE
How get name from GenericValue

### ISSUE THREAD

**Issue by michcleary** [pah/rapidjson#7]
I have code that used to be libjson that I'm converting to rapidjson.

typedef rapidjson::GenericValue<rapidjson::UTF8<>, rapidjson::CrtAllocator> JsonValue; 
         
 rapidjson::CrtAllocator& jsonAllocator()
 {
            static rapidjson::CrtAllocator instance;
            return instance;
}

I have a name value pair in the GenericValue object.  I need to get the name out to use it later.  How do I retrieve the name?  I don't see an accessor for this unless it's in a document object.

**Comment by pah** [comment]
A value has no name.  Only objects contain name-value pairs.  You can iterate over the members of an object via the `MemberBegin()` and `MemberEnd` iterators, see
 * http://rapidjson.org/md_doc_tutorial.html#QueryObject and 
 * http://rapidjson.org/structrapidjson_1_1_generic_member.html.

```cpp
  JsonValue v;
  // print name of first member:
  std::cout << v.MemberBegin()->name.GetString() << std::endl;
```

Please don't use this repository for support requests.  It is here for historical reasons only.
