### ISSUE TITLE
put

### ISSUE THREAD

**Issue by michcleary** [pah/rapidjson#8]
I have a boolean value that put into my document, but when I see if it isBool, it looks like rapidjson data has a bad value.  I don't see what is wrong with the way I'm doing this, do you?  I seem to be doing what [this person on stackOverflow does for int's](http://stackoverflow.com/questions/35727691/rapidjson-proper-json-creation)

one method:
rapidjson::Document::AllocatorType& allocator = m_document.GetAllocator();
std::string n1 = name; //passed into method
const char* l_cName = n1.c_str();
n2 = rapidjson::Value(rapidjson::StringRef(l_cName, strlen(l_cName)));
m_docment.AddMember(n2, true, allocator);

another method:
if(iter->value.IsBool())  //crashes here.  Looks like rapidjson data variable is bad
                    return((iter->value.GetBool()));  

private:
mutable rapidjson::Document m_document;

I thought I was running into a scope issue with my boolean variable, but it's still happening with just putting true there.

I tried adding the boolean to the document this way too, but it does the same thing when I check isBool like above later:
rapidjson::Value obj(rapidjson::kObjectType);
bool temp = v.cast<bool>();
obj.SetBool(temp);
m_document.AddMember(n2, obj, allocator);

I tried this too, but the same thing happens when I check isBool.  I think this is a bug in rapidjson.
bool temp = v.cast<bool>();
temp ? obj = rapidjson::Value(rapidjson::kFalseType) : obj = rapidjson::Value(rapidjson::kFalseType);
obj.SetBool(temp);
m_document.AddMember(n2, obj, allocator);

**Comment by michcleary** [comment]
Maybe it's an issue with allocator?

**Comment by pah** [comment]
Your code is incomplete, so it is hard to tell.  But on the other hand, there are so many issues in the quoted parts, that I would suggest that you do some C++ training first.

> `rapidjson::Document::AllocatorType& allocator = m_document.GetAllocator();`

I thought, you would be using the `jsonAllocator()` approach consistently?  What's this code now?

> ```cpp
> std::string n1 = name; //passed into method
> const char* l_cName = n1.c_str();
> n2 = rapidjson::Value(rapidjson::StringRef(l_cName, strlen(l_cName)));
> m_docment.AddMember(n2, true, allocator);
> ```

You must not use `StringRef` with temporary strings, see http://rapidjson.org/md_doc_tutorial.html#CreateString.
Instead, you would need to use
```cpp
n2 = rapidjson::Value(n2, allocator); // <-- copy the string
m_docment.AddMember(n2, true, allocator);
```

> `if(iter->value.IsBool()) //crashes here. Looks like rapidjson data variable is bad`

You need to be careful about your iterators.  You cannot keep them around when you add/remove elements from a JSON object.

> ```cpp
> private:
> mutable rapidjson::Document m_document;
> ``` 

Why do you declare the document `mutable`?  Are you sure, you know what you are doing?

> ```cpp
> rapidjson::Value obj(rapidjson::kObjectType);
> bool temp = v.cast();
> obj.SetBool(temp);
> m_document.AddMember(n2, obj, allocator);
> ```
* Why do you create `obj` as an object first and then set it to a `bool`?
* What is `v.cast()` doing?

> ```cpp
> bool temp = v.cast();
> temp ? obj = rapidjson::Value(rapidjson::kFalseType) : obj = rapidjson::Value(rapidjson::kFalseType);
> obj.SetBool(temp);
> ```
* Multiple assignments in a ternary operator
* Entirely unclear intent in the usage of the booleans and the JSON values here

I can't give you continuous support here, sorry.
